# fly.toml app configuration file generated for deno-rivals2-elobot on 2024-12-22T05:30:50Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'deno-rivals2-elobot'
primary_region = 'bos'

[build]

[http_service]
  internal_port = 1993
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
